ALTER TABLE "GenerationJob" ADD COLUMN "promptTokens" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "GenerationJob" ADD COLUMN "completionTokens" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "GenerationJob" ADD COLUMN "totalTokens" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "GenerationJob" ADD COLUMN "llmCallCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "GenerationJob" ADD COLUMN "lastTokenRecordedAt" DATETIME;

ALTER TABLE "NovelWorkflowTask" ADD COLUMN "promptTokens" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "NovelWorkflowTask" ADD COLUMN "completionTokens" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "NovelWorkflowTask" ADD COLUMN "totalTokens" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "NovelWorkflowTask" ADD COLUMN "llmCallCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "NovelWorkflowTask" ADD COLUMN "lastTokenRecordedAt" DATETIME;
